### ISSUE TITLE
English/Spanish translation

### ISSUE THREAD

**Issue by arhcstolen** [reactnativecn/reactnativecn.github.io#1]
You're amazing! It worked! Wouldn't mind if I write a translated post in English/Spanish? :)

**Comment by tdzl2003** [comment]
Sure. With a link to my github page(https://github.com/tdzl2003) on "author" would be nice.

**Comment by arhcstolen** [comment]
Done, see:
https://medium.com/@arhc/react-native-for-windows-users-1d8f91d5f043
https://medium.com/@arhc/c%C3%B3mo-usar-react-native-en-windows-f2d4f5e56c37

If there is something to fix or that you don't like on the articles, please tell me. Thank you! :-)
